### ISSUE TITLE
Hashtags in RTd statuses

### ISSUE THREAD

**Issue by fionapigott** [tw-ddis/tweet_parser#29]
Hi guys,

It seems like for a RTd status, the "entities" contain an @mention of the person being RTd (even though that isn't in the real text of the Tweet) and doesn't contain the hashtags that are in the RTd status.

Should we update our getter to include the (imo, more intuitive) entities that actually display in the Tweet? Or leave it alone?

Not urgent, and I can easily make this change. Just wondering what you guys think.

**Comment by binaryaaron** [comment]
Is this an artifact of the old retweet syntax?

```
RT: @someone some text that is really interesting
```

**Comment by fionapigott** [comment]
Yes, basically. I'm not 100% sure why our data payloads still look like that (it's not like our platform displays the Tweets that way)

**Comment by binaryaaron** [comment]
Closed by #30.
